# Generated by Django 5.2.1 on 2025-05-29 05:45

import sucursales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('direccion', models.CharField(help_text='Formato: [Grados]°[Minutos]\'[Segundos.decimales]"[N/S] [Grados]°[Minutos]\'[Segundos.decimales]"[E/O]', max_length=100, validators=[sucursales.models.validar_coordenadas_dms], verbose_name='Dirección (DMS)')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
    ]
