# Generated by Django 5.2.1 on 2025-05-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='visible',
            field=models.BooleanField(default=True, help_text='Indica si la sucursal es visible en el sistema', verbose_name='Visible'),
        ),
    ]
