# Generated by Django 5.0 on 2025-06-02 03:49

from django.db import migrations


def crear_sucursal_predeterminada(apps, schema_editor):
    Sucursal = apps.get_model('sucursales', 'Sucursal')
    # Verificamos que no exista ya
    if not Sucursal.objects.filter(nombre="Sucursal Predeterminada").exists():
        Sucursal.objects.create(
            nombre="Sucursal de Ejemplo",
            direccion='34°36\'00.000"S 058°22\'00.000"O',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(crear_sucursal_predeterminada),
    ]
