# Generated by Django 5.0 on 2025-06-02 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0002_sucursal_visible'),
        ('sucursales', '0003_crear_sucursal_default'),
    ]

    operations = [
    ]
