# Generated by Django 5.2.1 on 2025-06-03 02:01

import sucursales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0004_merge_20250602_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='direccion',
            field=models.CharField(help_text='Formato DMS: [Grados]°[Minutos]\'[Segundos.decimal]"[N/S] [Grados]°[Minutos]\'[Segundos.decimal]"[E/O] (p. ej.: 34°36\'00.000"S 058°22\'00.000"O)', max_length=50, validators=[sucursales.models.validar_coordenadas_dms], verbose_name='Dirección (DMS)'),
        ),
    ]
