# Generated by Django 5.2.1 on 2025-05-29 05:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaquinaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('precio_por_dia', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio por día')),
                ('descripcion_corta', models.CharField(max_length=200, verbose_name='Descripción corta')),
                ('descripcion_larga', models.TextField(verbose_name='Descripción larga')),
                ('imagen', models.ImageField(upload_to='maquinas/', verbose_name='Imagen')),
                ('dias_alquiler_min', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad mínima de días de alquiler')),
                ('dias_alquiler_max', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad máxima de días de alquiler')),
            ],
            options={
                'verbose_name': 'Máquina Base',
                'verbose_name_plural': 'Máquinas Base',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True, verbose_name='Patente')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('alquilada', 'Alquilada'), ('mantenimiento', 'En Mantenimiento'), ('reparacion', 'En Reparación'), ('baja', 'Dada de Baja')], default='disponible', max_length=20, verbose_name='Estado')),
                ('maquina_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='maquinas.maquinabase', verbose_name='Máquina base')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursales.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
            },
        ),
    ]
