# Generated by Django 5.2.1 on 2025-06-06 00:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0008_merge_20250605_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaquinaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('excavadora', 'Excavadora'), ('retroexcavadora', 'Retroexcavadora'), ('cargadora', 'Cargadora'), ('compactadora', 'Compactadora'), ('motoniveladora', 'Motoniveladora'), ('pavimentadora', 'Pavimentadora'), ('grua', 'Grúa'), ('hormigonera', 'Hormigonera'), ('dumper', 'Dumper'), ('manipulador', 'Manipulador Telescópico')], max_length=20)),
                ('marca', models.CharField(choices=[('caterpillar', 'Caterpillar'), ('komatsu', 'Komatsu'), ('volvo', 'Volvo'), ('hitachi', 'Hitachi'), ('liebherr', 'Liebherr'), ('jcb', 'JCB'), ('case', 'Case'), ('doosan', 'Doosan'), ('john_deere', 'John Deere'), ('kubota', 'Kubota')], max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('precio_por_dia', models.DecimalField(decimal_places=2, error_messages={'decimal_places': 'El precio no puede tener más de 2 decimales.', 'invalid': 'Por favor, ingrese un precio válido.', 'max_digits': 'El precio no puede tener más de 10 dígitos enteros.', 'max_whole_digits': 'La parte entera del precio no puede tener más de 10 dígitos.'}, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion_corta', models.TextField()),
                ('descripcion_larga', models.TextField()),
                ('imagen', models.ImageField(upload_to='maquinas/')),
                ('dias_alquiler_min', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad mínima de días de alquiler')),
                ('dias_alquiler_max', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad máxima de días de alquiler')),
                ('stock', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Máquina Base',
                'verbose_name_plural': 'Máquinas Base',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True, verbose_name='Patente')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('alquilada', 'Alquilada'), ('mantenimiento', 'En Mantenimiento'), ('adeudada', 'Adeudada')], default='disponible', max_length=20, verbose_name='Estado')),
                ('visible', models.BooleanField(default=True, help_text='Indica si la unidad es visible en el sistema', verbose_name='Visible')),
                ('maquina_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='maquinas.maquinabase', verbose_name='Máquina base')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('confirmado', 'Confirmado'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('mercadopago', 'Mercado Pago'), ('binance', 'Binance Pay')], max_length=20)),
                ('monto_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('preference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alquileres_maquinas', to='persona.persona')),
                ('maquina_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maquinas.maquinabase')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maquinas.unidad')),
            ],
            options={
                'verbose_name': 'Alquiler',
                'verbose_name_plural': 'Alquileres',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
