# Generated by Django - Manual migration
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='cantidad_dias',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='codigo_retiro',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='estado',
            field=models.CharField(
                choices=[
                    ('reservado', 'Reservado'),
                    ('en_curso', 'En Curso'),
                    ('finalizado', 'Finalizado'),
                    ('cancelado', 'Cancelado'),
                ],
                default='reservado',
                max_length=20
            ),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='numero',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ] 