# Generated by Django 5.0 on 2025-06-08 01:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinabase',
            name='dias_reembolso_parcial',
            field=models.PositiveIntegerField(default=5, help_text='Cantidad de días de antelación necesarios para obtener reembolso parcial', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Días mínimos para reembolso parcial'),
        ),
        migrations.AddField(
            model_name='maquinabase',
            name='dias_reembolso_total',
            field=models.PositiveIntegerField(default=10, help_text='Cantidad de días de antelación necesarios para obtener reembolso total', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Días mínimos para reembolso total'),
        ),
        migrations.AddField(
            model_name='maquinabase',
            name='porcentaje_reembolso_parcial',
            field=models.PositiveIntegerField(default=50, help_text='Porcentaje del monto total que será devuelto en caso de reembolso parcial', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Porcentaje de reembolso parcial'),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='descripcion_corta',
            field=models.TextField(verbose_name='Descripción corta'),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='descripcion_larga',
            field=models.TextField(verbose_name='Descripción larga'),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='maquinas/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='marca',
            field=models.CharField(choices=[('caterpillar', 'Caterpillar'), ('komatsu', 'Komatsu'), ('john_deere', 'John Deere'), ('volvo', 'Volvo'), ('hitachi', 'Hitachi'), ('case', 'Case'), ('jcb', 'JCB'), ('bobcat', 'Bobcat'), ('doosan', 'Doosan'), ('liebherr', 'Liebherr')], max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='modelo',
            field=models.CharField(max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='tipo',
            field=models.CharField(choices=[('excavadora', 'Excavadora'), ('retroexcavadora', 'Retroexcavadora'), ('cargadora', 'Cargadora'), ('compactadora', 'Compactadora'), ('grua', 'Grúa'), ('montacargas', 'Montacargas'), ('plataforma_elevadora', 'Plataforma Elevadora'), ('generador', 'Generador'), ('compresor', 'Compresor'), ('martillo_hidraulico', 'Martillo Hidráulico')], max_length=50, verbose_name='Tipo'),
        ),
    ]
