# Generated by Django 5.2.1 on 2025-05-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinabase',
            name='visible',
            field=models.BooleanField(default=True, help_text='Indica si la máquina base es visible en el sistema', verbose_name='Visible'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='visible',
            field=models.BooleanField(default=True, help_text='Indica si la unidad es visible en el sistema', verbose_name='Visible'),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='marca',
            field=models.CharField(choices=[('caterpillar', 'Caterpillar'), ('john_deere', 'John Deere'), ('bobcat', 'Bobcat'), ('stihl', 'STIHL'), ('husqvarna', 'Husqvarna'), ('volvo', 'Volvo Construction')], max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='tipo',
            field=models.CharField(choices=[('bordeadora', 'Bordeadora'), ('cortacesped', 'Cortacésped'), ('aplanadora', 'Aplanadora'), ('excavadora', 'Excavadora'), ('minicargadora', 'Mini Cargadora'), ('retroexcavadora', 'Retroexcavadora')], max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('alquilada', 'Alquilada'), ('mantenimiento', 'En Mantenimiento'), ('adeudada', 'Adeudada')], default='disponible', max_length=20, verbose_name='Estado'),
        ),
    ]
