# Generated by Django 5.2.1 on 2025-05-29 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0002_maquinabase_visible_unidad_visible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquinabase',
            name='visible',
        ),
    ]
