# Generated by Django 5.1.7 on 2025-06-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0002_alquiler_mejoras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('reservado', 'Reservado'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('rechazado', 'Rechazado')], default='reservado', max_length=20),
        ),
    ]
