# Generated by Django 5.0 on 2025-06-08 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0002_maquinabase_dias_reembolso_parcial_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alquiler',
        ),
    ]
