# Generated by Django 5.0 on 2025-05-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0003_remove_maquinabase_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinabase',
            name='descripcion_corta',
            field=models.TextField(verbose_name='Descripción corta'),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='marca',
            field=models.CharField(choices=[('caterpillar', 'Caterpillar'), ('john_deere', 'John Deere'), ('bobcat', 'Bobcat')], max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='tipo',
            field=models.CharField(choices=[('bordeadora', 'Bordeadora'), ('aplanadora', 'Aplanadora'), ('excavadora', 'Excavadora'), ('retroexcavadora', 'Retroexcavadora')], max_length=50, verbose_name='Tipo'),
        ),
    ]
