# Generated by Django 5.1.7 on 2025-06-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0003_alter_alquiler_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='cancelado_por_empleado',
            field=models.BooleanField(default=False, verbose_name='Cancelado por Empleado'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cancelación'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='monto_reembolso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto a Reembolsar'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='observaciones_cancelacion',
            field=models.TextField(blank=True, verbose_name='Observaciones de Cancelación'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='porcentaje_reembolso',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Porcentaje de Reembolso'),
        ),
    ]
