# Generated by Django 5.1.7 on 2025-06-08 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0004_agregar_campos_cancelacion_alquiler'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='empleado_que_cancelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alquileres_cancelados', to=settings.AUTH_USER_MODEL, verbose_name='Empleado que Canceló'),
        ),
    ]
