# Generated by Django 5.0 on 2025-06-08 02:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0004_alquiler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquinabase',
            name='dias_reembolso_parcial',
        ),
        migrations.RemoveField(
            model_name='maquinabase',
            name='dias_reembolso_total',
        ),
        migrations.AddField(
            model_name='maquinabase',
            name='dias_cancelacion_parcial',
            field=models.PositiveIntegerField(default=5, help_text='Número de días antes del inicio del alquiler para obtener reembolso parcial', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Días mínimos para reembolso parcial'),
        ),
        migrations.AddField(
            model_name='maquinabase',
            name='dias_cancelacion_total',
            field=models.PositiveIntegerField(default=10, help_text='Número de días antes del inicio del alquiler para obtener reembolso total', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Días mínimos para reembolso total'),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='descripcion_corta',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='descripcion_larga',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='maquinas/'),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='marca',
            field=models.CharField(choices=[('caterpillar', 'Caterpillar'), ('komatsu', 'Komatsu'), ('volvo', 'Volvo'), ('hitachi', 'Hitachi'), ('liebherr', 'Liebherr'), ('jcb', 'JCB'), ('case', 'Case'), ('doosan', 'Doosan'), ('john_deere', 'John Deere'), ('kubota', 'Kubota')], max_length=20),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='modelo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='porcentaje_reembolso_parcial',
            field=models.PositiveIntegerField(default=50, help_text='Porcentaje del monto total que se reembolsará en caso de cancelación parcial', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Porcentaje de reembolso parcial'),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='tipo',
            field=models.CharField(choices=[('excavadora', 'Excavadora'), ('retroexcavadora', 'Retroexcavadora'), ('cargadora', 'Cargadora'), ('compactadora', 'Compactadora'), ('motoniveladora', 'Motoniveladora'), ('pavimentadora', 'Pavimentadora'), ('grua', 'Grúa'), ('hormigonera', 'Hormigonera'), ('dumper', 'Dumper'), ('manipulador', 'Manipulador Telescópico')], max_length=20),
        ),
    ]
