# Generated by Django 5.0 on 2025-06-02 00:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0004_alter_maquinabase_descripcion_corta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinabase',
            name='stock',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Stock disponible'),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='dias_alquiler_max',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='La cantidad máxima de días debe ser mayor o igual a 1')], verbose_name='Cantidad máxima de días de alquiler'),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='dias_alquiler_min',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='La cantidad mínima de días debe ser mayor o igual a 1')], verbose_name='Cantidad mínima de días de alquiler'),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='precio_por_dia',
            field=models.DecimalField(decimal_places=2, error_messages={'decimal_places': 'No puede ingresar más de dos decimales.', 'invalid': 'Ingrese un número válido. Puede usar coma (,) o punto (.) como separador decimal.', 'max_decimal_places': 'No puede ingresar más de dos decimales.', 'max_digits': 'El número es demasiado grande. Debe tener como máximo 10 dígitos en total.'}, help_text='Ingrese el monto sin puntos. Puede usar coma (,) o punto (.) como separador decimal.', max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='El precio debe ser mayor o igual a cero.')], verbose_name='Precio por día'),
        ),
    ]
