# Generated by Django 5.0 on 2025-06-02 02:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0005_maquinabase_stock_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maquinabase',
            options={'ordering': ['nombre'], 'verbose_name': 'Máquina Base', 'verbose_name_plural': 'Máquinas Base'},
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='descripcion_corta',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='descripcion_larga',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='dias_alquiler_max',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='dias_alquiler_min',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='imagen',
            field=models.ImageField(upload_to='maquinas/'),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='marca',
            field=models.CharField(choices=[('caterpillar', 'Caterpillar'), ('komatsu', 'Komatsu'), ('volvo', 'Volvo'), ('hitachi', 'Hitachi'), ('liebherr', 'Liebherr'), ('jcb', 'JCB'), ('case', 'Case'), ('doosan', 'Doosan'), ('john_deere', 'John Deere'), ('kubota', 'Kubota')], max_length=20),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='modelo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='precio_por_dia',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='stock',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='tipo',
            field=models.CharField(choices=[('excavadora', 'Excavadora'), ('retroexcavadora', 'Retroexcavadora'), ('cargadora', 'Cargadora'), ('compactadora', 'Compactadora'), ('motoniveladora', 'Motoniveladora'), ('pavimentadora', 'Pavimentadora'), ('grua', 'Grúa'), ('hormigonera', 'Hormigonera'), ('dumper', 'Dumper'), ('manipulador', 'Manipulador Telescópico')], max_length=20),
        ),
    ]
