# Generated by Django 5.1.7 on 2025-06-08 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0005_agregar_empleado_que_cancelo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto a Reembolsar')),
                ('porcentaje', models.PositiveIntegerField(verbose_name='Porcentaje de Reembolso')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('pagado', 'Pagado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('alquiler', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reembolso', to='maquinas.alquiler', verbose_name='Alquiler')),
                ('empleado_que_marco_pagado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reembolsos_marcados_pagados', to=settings.AUTH_USER_MODEL, verbose_name='Empleado que Marcó como Pagado')),
            ],
            options={
                'verbose_name': 'Reembolso',
                'verbose_name_plural': 'Reembolsos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
