# Generated by Django 5.0 on 2025-06-08 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0005_remove_maquinabase_dias_reembolso_parcial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquinabase',
            name='id',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='id',
        ),
        migrations.AddField(
            model_name='maquinabase',
            name='id_maquina',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='unidad',
            name='id_unidad',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='precio_por_dia',
            field=models.DecimalField(decimal_places=2, error_messages={'decimal_places': 'El precio no puede tener más de 2 decimales.', 'invalid': 'Por favor, ingrese un precio válido.', 'max_digits': 'El precio no puede tener más de 10 dígitos enteros.', 'max_whole_digits': 'La parte entera del precio no puede tener más de 10 dígitos.'}, help_text='El precio debe ingresarse sin puntos. Puede utilizar comas para separar decimales.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
