# Generated by Django 5.0 on 2025-06-02 02:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0006_alter_maquinabase_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinabase',
            name='dias_alquiler_max',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad máxima de días de alquiler'),
        ),
        migrations.AlterField(
            model_name='maquinabase',
            name='dias_alquiler_min',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad mínima de días de alquiler'),
        ),
    ]
