# Generated by Django 5.0 on 2025-06-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0006_remove_maquinabase_id_remove_unidad_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinabase',
            name='id_maquina',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='id_unidad',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
