# Generated by Django 5.0 on 2025-06-02 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0007_alter_maquinabase_dias_alquiler_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinabase',
            name='precio_por_dia',
            field=models.DecimalField(decimal_places=2, error_messages={'decimal_places': 'El precio no puede tener más de 2 decimales.', 'invalid': 'Por favor, ingrese un precio válido.', 'max_digits': 'El precio no puede tener más de 10 dígitos en total.', 'max_whole_digits': 'La parte entera del precio no puede tener más de 8 dígitos.'}, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
