# Generated by Django 5.0 on 2025-06-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0007_alquiler_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinabase',
            name='visible',
            field=models.BooleanField(default=True, help_text='Indica si la máquina base es visible en el sistema', verbose_name='Visible'),
        ),
    ]
