# Generated by Django 5.0 on 2025-06-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0008_maquinabase_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinabase',
            name='imagen',
            field=models.ImageField(blank=True, error_messages={'invalid': 'Por favor, suba una imagen válida de la máquina.', 'invalid_image': 'Por favor, suba una imagen válida de la máquina.', 'required': 'La imagen es obligatoria.'}, null=True, upload_to='maquinas/', verbose_name='Imagen'),
        ),
    ]
