# Generated by Django 5.1.7 on 2025-06-05 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0009_alter_maquinabase_precio_por_dia'),
        ('persona', '0005_delete_empleado_persona_es_admin_persona_es_baneado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('confirmado', 'Confirmado'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('mercadopago', 'Mercado Pago'), ('binance', 'Binance Pay')], max_length=20)),
                ('monto_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('preference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('maquina_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maquinas.maquinabase')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alquileres_maquinas', to='persona.persona')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maquinas.unidad')),
            ],
            options={
                'verbose_name': 'Alquiler',
                'verbose_name_plural': 'Alquileres',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
