# Generated by Django 5.1.7 on 2025-06-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0010_alquiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='cantidad_dias',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad de días'),
        ),
    ]
