# Generated by Django 5.1.7 on 2025-06-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0011_alquiler_cantidad_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='codigo_retiro',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='Código de retiro'),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='estado',
            field=models.CharField(choices=[('reservado', 'Reservado'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='reservado', max_length=20),
        ),
    ]
