# Generated by Django 5.1.7 on 2025-07-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0012_agregar_estado_adeudado'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='fecha_fin_mantenimiento',
            field=models.DateField(blank=True, help_text='Fecha hasta la cual la unidad estará en mantenimiento', null=True, verbose_name='Fecha Fin Mantenimiento'),
        ),
    ]
