# Generated by Django 4.2.4 on 2025-01-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0013_unidad_fecha_fin_mantenimiento'),
    ]

    operations = [
        # Esta migración está vacía ya que el campo ya existe en la migración anterior
    ]
