# Generated by Django 5.1.7 on 2025-06-08 07:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import persona.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('modelo', models.IntegerField()),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('alquilada', 'Alquilada'), ('mantenimiento', 'En Mantenimiento')], default='disponible', max_length=20)),
                ('precio_dia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dias_minimos', models.IntegerField(default=1)),
                ('descripcion', models.TextField(default='Sin descripción disponible')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='maquinas/')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, editable=False, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, editable=False, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('es_cliente', models.BooleanField(default=False)),
                ('es_empleado', models.BooleanField(default=False)),
                ('es_admin', models.BooleanField(default=False)),
                ('es_baneado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Sucursal')),
                ('direccion', models.CharField(help_text='Dirección completa de la sucursal', max_length=200)),
                ('latitud', models.FloatField(help_text='Latitud de la ubicación (entre -90 y 90 grados)', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitud', models.FloatField(help_text='Longitud de la ubicación (entre -180 y 180 grados)', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('telefono', models.CharField(help_text='Número de teléfono de la sucursal (formato: +54 9 221 123-4567)', max_length=20, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido (mínimo 10 dígitos)', regex='^\\+?[\\d\\s-]{10,}$')])),
                ('email', models.EmailField(help_text='Correo electrónico de contacto', max_length=254, validators=[persona.models.validar_email])),
                ('horario', models.TextField(help_text='Horarios de atención de la sucursal')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('confirmado', 'Confirmado'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('mercadopago', 'Mercado Pago'), ('binance', 'Binance Pay')], max_length=20)),
                ('monto_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('preference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.maquina')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
            ],
            options={
                'verbose_name': 'Alquiler',
                'verbose_name_plural': 'Alquileres',
            },
        ),
    ]
