# Generated by Django 5.1.3 on 2025-06-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_codigoverificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='es_baneado',
        ),
        migrations.AddField(
            model_name='persona',
            name='bloqueado_cliente',
            field=models.BooleanField(default=False, help_text='Si el usuario está bloqueado para actuar como cliente'),
        ),
        migrations.AddField(
            model_name='persona',
            name='bloqueado_empleado',
            field=models.BooleanField(default=False, help_text='Si el usuario está bloqueado para actuar como empleado'),
        ),
    ]
