# Generated by Django 5.1.7 on 2025-05-29 00:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_alter_persona_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maquina',
            options={'verbose_name': 'Máquina', 'verbose_name_plural': 'Máquinas'},
        ),
        migrations.AddField(
            model_name='maquina',
            name='descripcion',
            field=models.TextField(default='Sin descripción disponible'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='dias_minimos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='maquina',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('alquilada', 'Alquilada'), ('mantenimiento', 'En Mantenimiento')], default='disponible', max_length=20),
        ),
        migrations.AddField(
            model_name='maquina',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='maquina',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='maquinas/'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='precio_dia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('confirmado', 'Confirmado'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('mercadopago', 'Mercado Pago'), ('binance', 'Binance Pay')], max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.maquina')),
            ],
            options={
                'verbose_name': 'Alquiler',
                'verbose_name_plural': 'Alquileres',
            },
        ),
    ]
