# Generated by Django 5.2.1 on 2025-05-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_alter_persona_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
