# Generated by Django 5.2.1 on 2025-05-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_alter_persona_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='persona',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
