# Generated by Django 5.1.3 on 2025-07-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_remove_persona_es_baneado_persona_bloqueado_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='es_visible',
            field=models.BooleanField(default=True, help_text='Indica si la sucursal es visible en listados y mapas', verbose_name='Visible'),
        ),
    ]
