# Generated by Django 5.2.1 on 2025-05-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_empleado_email_empleado_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='edad',
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
