# Generated by Django 5.0 on 2025-05-29 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_create_default_admins'),
        ('persona', '0003_alter_empleado_options_remove_empleado_edad_and_more'),
    ]

    operations = [
    ]
