# Generated by Django 5.1.7 on 2025-05-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_alter_maquina_options_maquina_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='preference_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
