# Generated by Django 5.2.1 on 2025-06-01 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_alter_empleado_options_remove_empleado_edad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(help_text='Dirección completa de la sucursal', max_length=200)),
                ('latitud', models.FloatField(help_text='Latitud de la ubicación (entre -90 y 90 grados)', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitud', models.FloatField(help_text='Longitud de la ubicación (entre -180 y 180 grados)', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('telefono', models.CharField(help_text='Número de teléfono de la sucursal', max_length=20)),
                ('email', models.EmailField(help_text='Correo electrónico de contacto', max_length=254)),
                ('horario_semana', models.CharField(help_text="Horario de atención de lunes a viernes (ej: '9:00 - 18:00')", max_length=50)),
                ('horario_sabado', models.CharField(blank=True, help_text="Horario de atención los sábados (ej: '9:00 - 13:00')", max_length=50, null=True)),
                ('horario_domingo', models.CharField(blank=True, help_text='Horario de atención los domingos', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
    ]
