# Generated by Django 5.2.1 on 2025-06-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_sucursal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='horario_domingo',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='horario_sabado',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='horario_semana',
        ),
        migrations.AddField(
            model_name='sucursal',
            name='horario',
            field=models.TextField(default='9:00-18:00', help_text='Horarios de atención de la sucursal'),
            preserve_default=False,
        ),
    ]
