# Generated by Django 5.1.7 on 2025-07-07 00:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_persona_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='calificacion_promedio',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Promedio de calificaciones del cliente (1.00 - 5.00)', max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
