# Generated by Django 5.2.1 on 2025-05-21 23:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_remove_null_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.CharField(help_text='El apellido debe tener entre 2 y 50 caracteres', max_length=50, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.CharField(help_text='Ingrese un DNI de entre 7 y 9 dígitos', max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe tener entre 7 y 9 dígitos numéricos', regex='^\\d{7,9}$')]),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(help_text='El nombre debe tener entre 2 y 50 caracteres', max_length=50, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
