# Generated by Django 5.2.1 on 2025-06-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_merge_20250529_0551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.AddField(
            model_name='persona',
            name='es_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persona',
            name='es_baneado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persona',
            name='es_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persona',
            name='es_empleado',
            field=models.BooleanField(default=False),
        ),
    ]
