# Generated by Django 5.1.7 on 2025-05-29 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_alquiler_preference_id_alter_alquiler_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alquiler',
            name='cliente',
        ),
        migrations.AddField(
            model_name='alquiler',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.persona'),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
