# Generated by Django 5.1.7 on 2025-06-05 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_delete_empleado_persona_es_admin_persona_es_baneado_and_more'),
        ('persona', '0005_remove_alquiler_cliente_alquiler_persona_and_more'),
    ]

    operations = [
    ]
