# Generated by Django 5.2.1 on 2025-06-01 23:07

import django.core.validators
import persona.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_remove_sucursal_horario_domingo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='id',
        ),
        migrations.AddField(
            model_name='sucursal',
            name='id_sucursal',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Sucursal'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='email',
            field=models.EmailField(help_text='Correo electrónico de contacto', max_length=254, validators=[persona.models.validar_email]),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='telefono',
            field=models.CharField(help_text='Número de teléfono de la sucursal (formato: +54 9 221 123-4567)', max_length=20, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido (mínimo 10 dígitos)', regex='^\\+?[\\d\\s-]{10,}$')]),
        ),
    ]
