# Generated by Django 5.1.3 on 2025-07-14 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_sucursal_es_visible'),
        ('persona', '0005_persona_calificacion_promedio'),
    ]

    operations = [
    ]
