# Generated by Django 5.2.1 on 2025-05-21 23:25

import persona.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_alter_persona_apellido_alter_persona_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(help_text='Ingrese su fecha de nacimiento (debe ser mayor de 18 años)', validators=[persona.models.validar_mayor_edad]),
        ),
    ]
