# Generated by Django 5.2.1 on 2025-06-05 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_remove_sucursal_id_sucursal_id_sucursal_and_more'),
        ('persona', '0007_alter_persona_direccion_alter_persona_telefono'),
    ]

    operations = [
    ]
