# Generated by Django 5.0 on 2025-06-08 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0003_delete_alquiler'),
        ('persona', '0008_merge_20250605_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alquiler',
            name='maquina',
        ),
        migrations.AddField(
            model_name='alquiler',
            name='maquina_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alquileres_persona', to='maquinas.maquinabase', verbose_name='Máquina base'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alquileres_persona', to='maquinas.unidad', verbose_name='Unidad'),
        ),
        migrations.DeleteModel(
            name='Maquina',
        ),
    ]
