# Generated by Django 5.0 on 2025-06-08 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0009_remove_alquiler_maquina_alquiler_maquina_base_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alquiler',
        ),
    ]
